### ISSUE TITLE
Doesn't seem possible to use a S3 repo for storing metalinks (just file mirroring).

### ISSUE THREAD

**Issue by ragaskar** [dpb587/metalink-repository-resource#8]
See issue filed here: https://github.com/dpb587/metalink/issues/4

I'm getting `in: bad repository: load: Unmarshaling: Unmarshaling XML: EOF` when specifying an S3 repo to store the metalink. 

Just dropping an issue here as well since it was one of the first places I looked to see if anyone else was having this problem. 😄

**Comment by dpb587** [comment]
Not that you need it anymore, but should be fixed in v1.20230612.1 by way of dependency updates in #9.
